// Date: 5/18/2014 9:13:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package roryee.timeghost.client.renderer.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTimeGhost extends ModelBase {
    //fields
    ModelRenderer Head = new ModelRenderer(this, "Head");
    ModelRenderer Torso = new ModelRenderer(this, "Torso");

    public ModelTimeGhost() {
        textureWidth = 64;
        textureHeight = 32;
        setTextureOffset("Head.Front", 0, 0);
        setTextureOffset("Head.End", 0, 12);
        setTextureOffset("Head.Mid1", 0, 20);
        setTextureOffset("Head.Mid2", 24, 0);
        setTextureOffset("Head.Trail1", 16, 12);

        setTextureOffset("Torso.Core", 20, 12);
        setTextureOffset("Torso.Under1", 24, 9);
        setTextureOffset("Torso.Back1", 42, 0);
        setTextureOffset("Torso.Back2", 42, 12);

        Head.setRotationPoint(0F, 0F, 0F);
        setRotation(Head, 0F, 0F, 0F);
        Head.mirror = true;
        Head.addBox("Front", -4F, -4F, -5F, 8, 8, 4);
        Head.addBox("End", -2F, -1F, 4F, 4, 4, 4);
        Head.addBox("Mid1", -4F, -3F, -1F, 8, 7, 2);
        Head.addBox("Mid2", -3F, -2F, 1F, 6, 6, 3);
        Head.addBox("Trail1", 0F, 1F, 10F, 1, 1, 1);

        Torso.setRotationPoint(0F, 9F, 0F);
        Torso.rotateAngleX = (float)Math.PI/9f;
        Torso.mirror = true;
        Torso.addBox("Core", -3F, -3F, -4F, 6, 15, 6);
        Torso.addBox("Under1", -3F, 12F, 1F, 6, 1, 1);
        Torso.addBox("Back1", -3F, -1F, 2F, 6, 15, 1);
        Torso.addBox("Back2", -3F, 0F, 3F, 6, 15, 1);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Head.render(f5);
        Torso.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
